#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.1
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.80
yabai -m config window_border                off
yabai -m config window_border_width          20
yabai -m config active_window_border_color   0xaaffffff
yabai -m config normal_window_border_color   0x00555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  38
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06



# Exceptions


# Eww Bar Stuff
yabai -m signal --add event=window_focused action='eww update yabai_active="$(yabai -m query --windows --window | jq -r .app) / $(yabai -m query --windows --window | jq -r .title)"'
yabai -m signal --add event=application_front_switched action='eww update yabai_active="$(yabai -m query --windows --window | jq -r .app) / $(yabai -m query --windows --window | jq -r .title)"'
yabai -m signal --add event=window_title_changed action='eww update yabai_active="$(yabai -m query --windows --window | jq -r .app) / $(yabai -m query --windows --window | jq -r .title)"'

yabai -m signal --add event=space_changed action='eww update yabai_active_space="$(yabai -m query --spaces --space | jq .index)"'
yabai -m signal --add event=display_changed action='eww update yabai_active_space="$(yabai -m query --spaces --space | jq .index)"'


echo "yabai configuration loaded.."
